# lovelace_gen

type: entities
entities:
  - entity: input_number.irrigae_number_days_{{cycle}}
    name: 'Irrigation days sequence'
  - type: custom:hui-element
    card_type: horizontal-stack
    columns: 8
    cards:
      {% for idx in range(1,9) %}

      # --- ENABLED DAYS --------------------------------------------------
      - type: conditional
        conditions:
          - condition: numeric_state
            entity: input_number.irrigae_number_days_{{cycle}}
            above: {{idx-1}}
        card: 
          type: custom:button-card
          entity: binary_sensor.irrigae_today_{{cycle}}
          template:
            - optionbar_button
          icon: 'mdi:numeric-{{idx}}-circle'
          styles:
            card:
              - border: >
                  [[[ if (states['binary_sensor.irrigae_today_{{cycle}}'].attributes.current_day === {{idx}})
                        return "3px solid green";
                      return "0px";
                  ]]]

          variables:
            attribute: 'day{{idx}}'
            states:
              'off':
                iconColor: rgba(111,111,111,0.6)

          tap_action:
            action: call-service
            service: script.irrigae_toggle_irrigation_day
            service_data:
              cycle: {{cycle}}
              day: {{idx}}
          double_tap_action:
            action: call-service
            service: browser_mod.sequence
            service_data:
              sequence:
                - service: input_number.set_value
                  data: 
                    entity_id: input_number.irrigae_current_day_{{cycle}}
                    value: {{idx}}
                - service: browser_mod.close_popup  ## WORK-AROUNG: Browser_mod don't update the page when the entity changes, so better close the popup.
                
               
        #    action: call-service
        #    service: input_number.set_value
        #    service_data:
        #      entity_id: input_number.irrigae_current_day_{{cycle}}
        #      value: {{idx}}
             
      # --- DISABLED DAYS --------------------------------------------------
  
      - type: conditional
        conditions:
          - condition: numeric_state
            entity: input_number.irrigae_number_days_{{cycle}}
            below: {{idx}}
        card: 
          type: custom:button-card
          entity: binary_sensor.irrigae_today_{{cycle}}
          template:
            - optionbar_button
          variables:
            iconColor: "rgba(0,0,0,0.4)"
          styles:
            card:
              - border: 0px
          icon: 'mdi:numeric-{{idx}}'
          tap_action:
            action: none
          hold_action:
            action: none
        
      {% endfor %}


